[package]
name = "mint"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive", "string"] }
log = { version = "*", features = ["release_max_level_debug"] }
env_logger = "*"

rand = "*"
bytes = "1"
tokio = { version = "1", features = ["macros", "rt", "io-util", "net", "time"] }
chacha20poly1305 = "*"
aead = { version = "*", features = ["bytes"] }
base64 = "*"

socks5 = { path = "../socks5" }
